export type MenuItem = {
  id: number;
  category: string;
  name: string;
  price: number;
};

export const MENU_ITEMS: MenuItem[] = [
  { id: 1, category: "ビール", name: "ドラフトハイネケン", price: 750 },
  { id: 2, category: "ビール", name: "シャンディーガフ", price: 750 },
  { id: 3, category: "ビール", name: "レッドアイ", price: 750 },
  { id: 4, category: "ビール", name: "パインビア", price: 750 },
  { id: 5, category: "ビール", name: "コロナ", price: 850 },
  { id: 6, category: "ビール", name: "ヒューガルデンホワイト", price: 850 },
  { id: 7, category: "ビール", name: "ギネス", price: 850 },
  { id: 8, category: "レッドブル", name: "レッドブル", price: 550 },
  { id: 9, category: "レッドブル", name: "レッドブルウォッカ", price: 850 },
  { id: 10, category: "レッドブル", name: "レッドブルイエガー", price: 850 },
  { id: 11, category: "レッドブル", name: "レッドブルエナジー", price: 900 },
  { id: 12, category: "パーティーショット", name: "クエルボゴールド", price: 500 },
  { id: 13, category: "パーティーショット", name: "イエガーマイスター", price: 500 },
  { id: 14, category: "パーティーショット", name: "コカレロ", price: 600 },
  { id: 15, category: "パーティーショット", name: "クライナー各種", price: 800 },
  { id: 16, category: "パーティーショット", name: "ズブロッカ", price: 500 },
  { id: 17, category: "パーティーショット", name: "テキーラ 6ショット", price: 2500 },
  { id: 18, category: "パーティーショット", name: "イエガー 6ショット", price: 2500 },
  { id: 19, category: "パーティーショット", name: "コカレロ 6ショット", price: 3000 },
  { id: 20, category: "果実酒", name: "梅酒", price: 750 },
  { id: 21, category: "果実酒", name: "ゆず梅酒", price: 750 },
  { id: 22, category: "果実酒", name: "マンゴー梅酒", price: 750 },
  { id: 23, category: "クラシック", name: "ハイボール", price: 700 },
  { id: 24, category: "クラシック", name: "ウーロンハイ", price: 600 },
  { id: 25, category: "クラシック", name: "緑茶ハイ", price: 600 },
  { id: 26, category: "クラシック", name: "ジャスミンハイ", price: 600 },
  { id: 27, category: "クラシック", name: "紅茶ハイ", price: 600 },
  { id: 28, category: "クラシック", name: "ひげ茶ハイ", price: 600 },
  { id: 29, category: "クラシック", name: "レモンサワー", price: 700 },
  { id: 30, category: "クラシック", name: "杏仁レモンサワー", price: 700 },
  { id: 31, category: "クラシック", name: "グレープフルーツサワー", price: 700 },
  { id: 32, category: "クラシック", name: "ライムサワー", price: 700 },
  { id: 33, category: "ジン", name: "ビィフィーター", price: 750 },
  { id: 34, category: "ジン", name: "タンカレー", price: 750 },
  { id: 35, category: "ジン", name: "ボンベイサファイア", price: 750 },
  { id: 36, category: "ジン", name: "エンブレス", price: 850 },
  { id: 37, category: "ジン", name: "六 -ロク-", price: 850 },
  { id: 38, category: "スピリッツベース", name: "ジントニック", price: 750 },
  { id: 39, category: "スピリッツベース", name: "ジンバック", price: 750 },
  { id: 40, category: "スピリッツベース", name: "オレンジブロッサム", price: 750 },
  { id: 41, category: "スピリッツベース", name: "ジンフィズ", price: 800 },
  { id: 42, category: "スピリッツベース", name: "テキーラサンライズ", price: 750 },
  { id: 43, category: "スピリッツベース", name: "キューバリブレ", price: 750 },
  { id: 44, category: "スピリッツベース", name: "ソルクバーノ", price: 750 },
  { id: 45, category: "スピリッツベース", name: "X.Y.Z.", price: 800 },
  { id: 46, category: "スピリッツベース", name: "モスコミュール", price: 750 },
  { id: 47, category: "スピリッツベース", name: "スクリュードライバー", price: 750 },
  { id: 48, category: "スピリッツベース", name: "ソルティードッグ", price: 750 },
  { id: 49, category: "スピリッツベース", name: "ブラッディメアリー", price: 750 },
  { id: 50, category: "スピリッツベース", name: "カミカゼ", price: 850 },
  { id: 51, category: "ウイスキー", name: "ジャックダニエル", price: 800 },
  { id: 52, category: "ウイスキー", name: "ジムビーム", price: 700 },
  { id: 53, category: "ウイスキー", name: "アーリータイムズ", price: 800 },
  { id: 54, category: "ウイスキー", name: "フォアローゼス", price: 750 },
  { id: 55, category: "ウイスキー", name: "ローゼスブラック", price: 800 },
  { id: 56, category: "ウイスキー", name: "I.W.ハーパー", price: 750 },
  { id: 57, category: "ウイスキー", name: "メーカーズマーク", price: 750 },
  { id: 58, category: "ウイスキー", name: "ワイルドターキー", price: 750 },
  { id: 59, category: "ウイスキー", name: "角", price: 700 },
  { id: 60, category: "ウイスキー", name: "サントリーオールド", price: 750 },
  { id: 61, category: "ウイスキー", name: "碧", price: 1000 },
  { id: 62, category: "ウイスキー", name: "宮城峡", price: 1000 },
  { id: 63, category: "ウイスキー", name: "白州", price: 1300 },
  { id: 64, category: "ウイスキー", name: "山崎", price: 1300 },
  { id: 65, category: "ウイスキー", name: "デュワーズ12年", price: 750 },
  { id: 66, category: "ウイスキー", name: "シーバスリーガル12年", price: 900 },
  { id: 67, category: "ウイスキー", name: "グレンフィディック12年", price: 900 },
  { id: 68, category: "ウイスキー", name: "グレンリベット12年", price: 900 },
  { id: 69, category: "ウイスキー", name: "アードベッグ10年", price: 1000 },
  { id: 70, category: "ウイスキー", name: "ラフロイグ10年", price: 1000 },
  { id: 71, category: "ウイスキー", name: "バランタイン17年", price: 1300 },
  { id: 72, category: "ウイスキー", name: "ジェムソン", price: 750 },
  { id: 73, category: "ウイスキー", name: "ジェムソンスタウト", price: 850 },
  { id: 74, category: "ウイスキー", name: "カネマラ", price: 900 },
  { id: 75, category: "カクテル", name: "カシスオレンジ", price: 750 },
  { id: 76, category: "カクテル", name: "カシスグレープフルーツ", price: 750 },
  { id: 77, category: "カクテル", name: "スプモーニ", price: 750 },
  { id: 78, category: "カクテル", name: "カンパリオレンジ", price: 750 },
  { id: 79, category: "カクテル", name: "ミスティアジンジャー", price: 750 },
  { id: 80, category: "カクテル", name: "マリブコーク", price: 750 },
  { id: 81, category: "カクテル", name: "マリブピニャコラーダ", price: 800 },
  { id: 82, category: "カクテル", name: "ピーチウーロン", price: 750 },
  { id: 83, category: "カクテル", name: "ファジーネーブル", price: 750 },
  { id: 84, category: "カクテル", name: "マンゴヤンオレンジ", price: 750 },
  { id: 85, category: "カクテル", name: "チャイナ・ブルー", price: 750 },
  { id: 86, category: "カクテル", name: "アマレットジンジャー", price: 750 },
  { id: 87, category: "カクテル", name: "メロンボール", price: 750 },
  { id: 88, category: "カクテル", name: "バイオレッドフィズ", price: 800 },
  { id: 89, category: "カクテル", name: "ティフィンミルク", price: 750 },
  { id: 90, category: "カクテル", name: "ティフィンジンジャー", price: 750 },
  { id: 91, category: "カクテル", name: "カルーアミルク", price: 750 },
  { id: 92, category: "カクテル", name: "ベイリーズミルク", price: 800 },
  { id: 93, category: "カクテル", name: "スノーボール", price: 800 },
  { id: 94, category: "カクテル", name: "ヨーグルトパイン", price: 800 },
  { id: 95, category: "カクテル", name: "抹茶 -奏-", price: 800 },
  {
    id: 96,
    category: "シャンパン / スパークリングワイン",
    name: "サンテロ 天使のアスティ",
    price: 4500
  },
  {
    id: 97,
    category: "シャンパン / スパークリングワイン",
    name: "モエ・エ・シャンドン",
    price: 13000
  },
  {
    id: 98,
    category: "シャンパン / スパークリングワイン",
    name: "モエ・エ・シャンドン ネクターロゼ",
    price: 30000
  },
  {
    id: 99,
    category: "シャンパン / スパークリングワイン",
    name: "ヴーヴクリコ イエロー",
    price: 15000
  },
  {
    id: 100,
    category: "シャンパン / スパークリングワイン",
    name: "アルマンドゴールド",
    price: 88000
  },
  { id: 101, category: "ソフトドリンク", name: "ウーロン茶", price: 500 },
  { id: 102, category: "ソフトドリンク", name: "ジャスミン茶", price: 500 },
  { id: 103, category: "ソフトドリンク", name: "無糖紅茶", price: 500 },
  { id: 104, category: "ソフトドリンク", name: "ひげ茶", price: 500 },
  { id: 105, category: "ソフトドリンク", name: "コカ・コーラ", price: 500 },
  { id: 106, category: "ソフトドリンク", name: "ジンジャーエール", price: 500 },
  {
    id: 107,
    category: "ソフトドリンク",
    name: "ライムトニックウォーター",
    price: 500
  },
  { id: 108, category: "ソフトドリンク", name: "オレンジジュース", price: 500 },
  {
    id: 109,
    category: "ソフトドリンク",
    name: "グレープフルーツジュース",
    price: 500
  },
  { id: 110, category: "ソフトドリンク", name: "パインジュース", price: 500 },
  { id: 111, category: "ソフトドリンク", name: "アップルジュース", price: 500 },
  {
    id: 112,
    category: "ソフトドリンク",
    name: "クランベリージュース",
    price: 500
  },
  { id: 113, category: "ソフトドリンク", name: "トマトジュース", price: 500 },
  { id: 114, category: "ソフトドリンク", name: "ミルク", price: 500 }
];
